In [1]:
import numpy as np

In [5]:
a =np.random.rand(1024,768,3)

In [7]:
a.shape

(1024, 768, 3)

In [22]:
a

array([[[0.81912548, 0.7525094 , 0.11913326],
        [0.26308023, 0.04251717, 0.72485681],
        [0.05881383, 0.42653074, 0.62520104],
        ...,
        [0.1761438 , 0.74136719, 0.77806214],
        [0.71327886, 0.97848733, 0.45453989],
        [0.02260921, 0.44655275, 0.1437477 ]],

       [[0.98078059, 0.37604407, 0.44281199],
        [0.192455  , 0.10174748, 0.21272785],
        [0.56327734, 0.05860218, 0.55493298],
        ...,
        [0.6201977 , 0.86763102, 0.2571452 ],
        [0.87696889, 0.03084092, 0.01777751],
        [0.82507132, 0.59294614, 0.53346986]],

       [[0.5876631 , 0.15658218, 0.68710912],
        [0.68291113, 0.64429914, 0.44578439],
        [0.67894116, 0.76889489, 0.24574568],
        ...,
        [0.52655627, 0.8942563 , 0.46974251],
        [0.28407042, 0.27776302, 0.0748067 ],
        [0.82147279, 0.6910194 , 0.07458562]],

       ...,

       [[0.14446303, 0.61083292, 0.17386469],
        [0.75923373, 0.65140739, 0.42407353],
        [0.48764303, 0

In [12]:
b = a[:2]

In [13]:
b.shape

(2, 768, 3)

In [17]:
a[:,:,1]

array([[0.7525094 , 0.04251717, 0.42653074, ..., 0.74136719, 0.97848733,
        0.44655275],
       [0.37604407, 0.10174748, 0.05860218, ..., 0.86763102, 0.03084092,
        0.59294614],
       [0.15658218, 0.64429914, 0.76889489, ..., 0.8942563 , 0.27776302,
        0.6910194 ],
       ...,
       [0.61083292, 0.65140739, 0.68545744, ..., 0.69311704, 0.96682083,
        0.04071855],
       [0.20284213, 0.98167913, 0.20228872, ..., 0.51037027, 0.86099712,
        0.40128558],
       [0.50945108, 0.76293003, 0.43728639, ..., 0.11163699, 0.41836572,
        0.54959321]])

In [21]:
a[:,:,2]

array([[0.11913326, 0.72485681, 0.62520104, ..., 0.77806214, 0.45453989,
        0.1437477 ],
       [0.44281199, 0.21272785, 0.55493298, ..., 0.2571452 , 0.01777751,
        0.53346986],
       [0.68710912, 0.44578439, 0.24574568, ..., 0.46974251, 0.0748067 ,
        0.07458562],
       ...,
       [0.17386469, 0.42407353, 0.41980084, ..., 0.14248082, 0.778532  ,
        0.91229303],
       [0.56830156, 0.01939071, 0.82049922, ..., 0.53933507, 0.91118975,
        0.71813088],
       [0.20138928, 0.53584428, 0.38483625, ..., 0.91989111, 0.95474285,
        0.78368401]])

In [1]:
import numpy as np
import cv2
import glob

In [20]:
img = cv2.imread('data/memorial0061.png')
img = img.astype(np.int)
print(255*183/255)
print(img[:,:,0]*183/255)
print(88888)
print(img[:,:,1])
print(88888)
print(img[:,:,0]*2+img[:,:,1]*3)

183.0
[[183.          22.96470588  30.85882353 ...  52.38823529  54.54117647
   58.12941176]
 [183.          27.98823529  37.31764706 ...  63.15294118  69.61176471
   58.84705882]
 [183.          38.03529412  35.88235294 ...  52.38823529  59.56470588
   55.97647059]
 ...
 [183.          25.83529412  28.70588235 ... 100.47058824  94.01176471
   91.85882353]
 [183.          27.27058824  29.42352941 ... 100.47058824  96.88235294
   97.6       ]
 [183.          27.98823529  29.42352941 ... 183.         183.
  183.        ]]
88888
[[  0  52  72 ... 148 145 175]
 [  0  58  94 ... 191 202 187]
 [  0 100  90 ... 140 178 174]
 ...
 [  0  73  73 ... 254 250 247]
 [  0  74  76 ... 255 255 254]
 [  0  75  76 ...   0   0   0]]
88888
[[ 510  220  302 ...  590  587  687]
 [ 510  252  386 ...  749  800  725]
 [ 510  406  370 ...  566  700  678]
 ...
 [ 510  291  299 ... 1042 1012  997]
 [ 510  298  310 ... 1045 1035 1034]
 [ 510  303  310 ...  510  510  510]]


C:\Users\HanWen\AppData\Local\Temp\ipykernel_12400\1503014245.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  img = img.astype(np.int)


In [4]:
for i in range(img.shape[0]):       #height
        for j in range(img.shape[1]):   #width
            print(img[i][j][0])


255
32
43
55
46
44
41
41
42
43
43
43
40
37
36
37
34
34
39
39
40
40
40
38
41
39
40
39
39
36
36
37
37
40
36
35
40
41
43
41
41
36
37
37
39
40
40
42
42
40
40
40
41
38
37
36
38
38
39
37
36
37
38
36
39
41
39
40
41
41
37
37
41
42
44
40
38
38
40
37
35
35
38
43
38
36
38
37
39
48
58
68
76
70
73
82
72
80
106
99
80
70
70
64
63
59
60
62
57
52
64
63
76
76
77
80
93
67
78
118
142
145
156
137
137
140
145
133
115
109
148
141
137
142
137
132
128
118
126
121
157
124
111
110
104
120
132
145
144
113
96
94
92
91
91
96
96
97
103
96
103
82
98
108
102
124
117
97
109
135
146
132
114
127
116
107
91
85
111
148
156
141
145
145
146
151
143
139
143
159
134
91
85
102
130
139
126
92
95
101
105
110
94
99
94
90
88
84
85
92
105
93
90
92
108
100
108
115
98
98
111
119
104
114
103
99
113
124
125
118
117
117
110
107
107
102
113
115
113
111
116
111
108
104
102
99
98
98
95
93
89
86
75
69
69
75
75
72
63
79
82
81
103
106
102
100
101
97
99
100
86
81
89
49
41
45
48
50
51
49
46
43
48
49
50
48
47
48
53
54
50
49
47
42
45
48
52
53
44
4

KeyboardInterrupt: 